### ISSUE TITLE
last winter's line appears to end at or before today's date in some plots

### ISSUE THREAD

**Issue by douglasbagnall** [zmlabe/IceVarFigs#1]
In a couple of graphs on https://sites.uci.edu/zlabe/arctic-temperatures/ the brown line for winter 2017/18 disappears under the 2018/19 line and is never seen again.

https://sites.uci.edu/zlabe/files/2019/02/dmi_fdd_80N.png
https://sites.uci.edu/zlabe/files/2019/02/dmi_fdd_anomalies_80N_social.png

I wonder if there is a "2018" hard coded in the wrong place somewhere.

**Comment by zmlabe** [comment]
Yes, thank you! There was a coding error at the transition from 2018 to 2019. It should be fixed now.
