### ISSUE TITLE
SIV_PIOMAS_v2 Script

### ISSUE THREAD

**Issue by rhodrid** [zmlabe/IceVarFigs#4]
For me, this is one of the most powerful images in the collection: https://sites.uci.edu/zlabe/files/2019/10/SIV_PIOMAS_September_v2.png

Is the script to generate it in the repo? I've tried plot_SIV_PIOMAS.py but it outputs something a little different.

**Comment by zmlabe** [comment]
This script `plot_SIV_v2_PIOMAS.py` is now provided in https://github.com/zmlabe/IceVarFigs/blob/master/Scripts/SeaIce/plot_SIV_v2_PIOMAS.py

**Comment by rhodrid** [comment]
That's awesome, thanks!
